eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  cloud:
    gateway:
      routes:
      - id: user-service
        predicates:
        - Path=/users/**
        uri: lb://user-service
      - id: task-service
        predicates:
        - Path=/task/**
        uri: lb://task-service
