spring:
   application:
    name: user-service

   datasource:
    url: jdbc:mysql://localhost:3306/userudemy
    username: root
    password: 
        
   jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
 
server:
  port: 8082
  
eureka:
  client:
     service-url:
      defaultZone: http://localhost:8761/eureka
  

